### ISSUE TITLE
xvfb dependency - need for a wrapper around the xvfb magic

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/vivliostyle-formatter-issues#14]
The dependency on xvfb should be hidden from the user for the sake of ease, approachability and usability. There are a lot of non-technical people working on Linux that can just invoke some command-line tool. So the complete magic with starting xvfb, setting $DISPLAY etc. should be hidden in some wrapper script.

**Comment by skoji** [comment]
Fixed in 2016.1 . Just call vivliostyle-formatter. If there is no X server and xvfb is installed, vivliostyle-formatter uses xvfb.
