### ISSUE TITLE
Page counter issue in vs-formatter

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/vivliostyle-formatter-issues#23]
See 

https://www.print-css.rocks/lesson-page-numbers.html

The total number of pages is not rendered properly compared to the other converters.

**Comment by kwkbtr** [comment]
`pages` counter is not implemented yet. We want to support it in future releases.

**Comment by MurakamiShinyu** [comment]
This issue was moved to vivliostyle/vivliostyle.js#422

**Comment by kwkbtr** [comment]
We added support for `pages` counter in VersaType Converter 2018.5.
