### ISSUE TITLE
Support for repeating table header/footer?

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/vivliostyle-formatter-issues#24]
See

https://www.print-css.rocks/lesson-tables.html

Table header and footer are not repeated on subsequent pages.

**Comment by frivoal** [comment]
Currently, we do not support repeating table headers and footers, but we do want to support it.

CSS specifications do not define whether table headers and footers should be repeated across pages or not. It allows both behaviors, but doesn't pick favorites (https://www.w3.org/TR/CSS21/tables.html). Currently more browsers chose not to repeat than to, but most but it's the other way around for print formatters. 

We're not really happy with 2 behaviors that sort of depend on the type of CSS UA, so we want to explore with the CSSWG whether browsers are willing to align on repeating (in which case we will follow as well).

Alternatively or in addition, we also want to look into whether a new property allowing to switch between both behaviors could be introduced.

**Comment by frivoal** [comment]
https://lists.w3.org/Archives/Public/www-style/2016Jan/0135.html

**Comment by kwkbtr** [comment]
Supported in 2017.2.
