### ISSUE TITLE
Formatter --output broken

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/vivliostyle-formatter-issues#31]
It is not possible to create a PDF file with a custom --output parameter - neither with for a given directory nor for a target PDF file with full path.

Suxmac:tmp ajung$ vivliostyle-formatter  --output $HOME acid.html
specified output "/Users/ajung" is not in a directory

Suxmac:tmp ajung$ vivliostyle-formatter  --output $PWD acid.html
Loading url : http://file.vivf/Users/ajung/tmp/acid.html
[0124/123133:ERROR:simple_handler.cc(261)] print failed to /Users/ajung/tmp

Suxmac:tmp ajung$ vivliostyle-formatter  --output /tmp/out.pdf acid.html
specified output "/tmp/out.pdf" is not in a directory

**Comment by skoji** [comment]
This is a bug that occurs when you specify a file in a directory which is a direct child of the root directory.

`--output` specifies the path to the output PDF file, not directory.
So this will not work : `vivliostyle-formatter input.html --output=$HOME`
This should work: `vivliostyle-formatter input.html --output=$HOME/output.pdf`
This should also work: `vivliostyle-formatter input.html --output=/private/tmp/output.pdf`

But this does not work(which should work). : `vivliostyle-formatter input.html --output=/tmp/output.pdf`
