### ISSUE TITLE
No CSS gradient support?

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/vivliostyle-formatter-issues#35]
This file

https://gist.github.com/zopyx/23d3f3c3340ca1123744

is supposed to render a background with a gradient.

However VS only produces a plain green background.

**Comment by kwkbtr** [comment]
Gradient values are currently ignored, but we want to support them in future releases.

**Comment by kwkbtr** [comment]
Gradients are supported in 2016.4 release.
