### ISSUE TITLE
Ligature support?

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/vivliostyle-formatter-issues#39]
Is there support for ligatures available in vs-formatter 2016.1?

**Comment by kwkbtr** [comment]
2016.1 does not support ligatures.
The next Formatter release will enable ligatures by default.
Furthermore we are planning to support [`font-feature-settings` property](https://drafts.csswg.org/css-fonts/#font-feature-settings-prop), with which you can do finer control of OpenType font features. cf. vivliostyle/vivliostyle.js#151

**Comment by kwkbtr** [comment]
Supported in 2016.4.
