### ISSUE TITLE
2016.4: problem with widths of floating boxes

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/vivliostyle-formatter-issues#42]
See

https://github.com/zopyx/css-paged-media-tutorial/tree/vs2016.4/lesson-ligatures

There are float:left DIVs with a min-width: 45% - however some boxes overlap.

[vivliostyle-output.pdf](https://github.com/vivliostyle/vivliostyle-formatter-issues/files/209811/vivliostyle-output.pdf)

**Comment by kwkbtr** [comment]
Fixed in 2016.7.
