### ISSUE TITLE
paper size in mm unit makes incorrect, both predefined and custom

### ISSUE THREAD

**Issue by kmuto** [Trimmarks/vivliostyle-formatter-issues#51]
I suspect this is relate with #50 or conversion problem between mm <-> pt.

For example,
`vivliostyle-formatter --page-size=A5 index.html`
produces 147.814mm x 209.689mm, 419 pt x595 pt. (A5 should be 148mm x 210mm, 419.528pt x 595.276pt)
`@page { size: 148mm 210mm; }` returns same result.

It is bit small, but is enough that a printing firm may reject.

**Comment by kmuto** [comment]
(correction: 147.814mm x 209.903mm)

**Comment by kwkbtr** [comment]
I suspect this is the same issue as #50.

**Comment by MurakamiShinyu** [comment]
This issue was moved to vivliostyle/vivliostyle.js#433
