### ISSUE TITLE
thin dotted borders sometimes be disappeared

### ISSUE THREAD

**Issue by kmuto** [Trimmarks/vivliostyle-formatter-issues#56]
Some (not every) thin (<=1px or <0.6mm) dotted borders  are disappeared from output.
This happens only if border-style: dotted or dashed.
border-style: solid works.

Formatter 2016.10, both Debian Jessie and Mac OS X 10.9.5.

[dotted.zip](https://github.com/vivliostyle/vivliostyle-formatter-issues/files/593661/dotted.zip)

**Comment by MurakamiShinyu** [comment]
This issue was moved to vivliostyle/vivliostyle.js#436

**Comment by skoji** [comment]
We have fixed this in 2018.7 release of VersaType Converter.
