### ISSUE TITLE
Images missing in PDF

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/vivliostyle-formatter-issues#59]
See 
https://github.com/zopyx/print-css-rocks/tree/master/lesson-css-transformations

https://beta.print-css.rocks/lesson-css-transformations.html

The images on the last page are missing (VS 2017.2)

**Comment by MurakamiShinyu** [comment]
I'm testing this but I haven't found the problem, and in your test result page: https://print-css.rocks/lesson-css-transformations.html the images on the last page of vivliostyle result seem not to be missing.
