### ISSUE TITLE
formatter 0.1.4 not installing on CentOS 6.7

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/vivliostyle-formatter-issues#8]
[ajung@dev1 ~]$ cat /etc/issue
CentOS release 6.7 (Final)
Kernel \r on an \m

[ajung@dev1 ~]$ sudo rpm -U vivliostyle-formatter-0.1.4.x86_64.rpm
[sudo] password for ajung:
Sorry, try again.
[sudo] password for ajung:
error: Failed dependencies:
    libc.so.6(GLIBC_2.14)(64bit) is needed by vivliostyle-formatter-0.1.4-2.x86_64
    libstdc++.so.6(GLIBCXX_3.4.15)(64bit) is needed by vivliostyle-formatter-0.1.4-2.x86_64
    libstdc++.so.6(GLIBCXX_3.4.18)(64bit) is needed by vivliostyle-formatter-0.1.4-2.x86_64

**Comment by skoji** [comment]
I have checked on CentOS 6.7. Same with `sudo yum install vivliostyle-formatter-0.1.4.x86_64.rpm` . 

Seems that the version of libstdc++ in CentOS 6.7 is older than the version Chromium Embedded Framework requires.

I'll look further into this problem.

**Comment by skoji** [comment]
We're not going to support CentOS 6.x, for Chromium Embedded does not run on it.
